# Generated by Django 5.1.5 on 2025-02-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner', models.ImageField(upload_to='media/site/')),
                ('Caption', models.TextField()),
            ],
        ),
    ]
